# Generated by Django 4.2.1 on 2023-06-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_portal_category_alter_portal_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='bairro',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='rua',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
