# Generated by Django 4.2.1 on 2023-06-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_portal_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='status',
            field=models.CharField(default='Não resolvido', max_length=20),
        ),
    ]
