# Generated by Django 4.2.1 on 2023-09-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='feedback',
            field=models.TextField(default='Sem resposta ainda.'),
        ),
    ]
